server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  add_header Cross-Origin-Opener-Policy "same-origin-allow-popups" always;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|svg|webp|woff2?)$ {
    try_files $uri =404;
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}

