/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        base: {
          950: 'rgb(var(--color-base-950) / <alpha-value>)',
          900: 'rgb(var(--color-base-900) / <alpha-value>)',
          800: 'rgb(var(--color-base-800) / <alpha-value>)',
          700: 'rgb(var(--color-base-700) / <alpha-value>)',
          600: 'rgb(var(--color-base-600) / <alpha-value>)',
          500: 'rgb(var(--color-base-500) / <alpha-value>)',
        },
        brand: {
          300: 'rgb(var(--color-brand-300) / <alpha-value>)',
          400: 'rgb(var(--color-brand-400) / <alpha-value>)',
          500: 'rgb(var(--color-brand-500) / <alpha-value>)',
          600: 'rgb(var(--color-brand-600) / <alpha-value>)',
          700: 'rgb(var(--color-brand-700) / <alpha-value>)',
          800: 'rgb(var(--color-brand-800) / <alpha-value>)',
          900: 'rgb(var(--color-brand-900) / <alpha-value>)',
        },
        ink: {
          50:  'rgb(var(--color-ink-50) / <alpha-value>)',
          200: 'rgb(var(--color-ink-200) / <alpha-value>)',
          400: 'rgb(var(--color-ink-400) / <alpha-value>)',
          600: 'rgb(var(--color-ink-600) / <alpha-value>)',
          700: 'rgb(var(--color-ink-700) / <alpha-value>)',
          800: 'rgb(var(--color-ink-800) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['"SF Pro Display"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        mono: ['"SF Mono"', '"Fira Code"', 'Consolas', 'monospace'],
      },
      animation: {
        'fade-in':      'fadeIn 0.4s ease-out both',
        'slide-up':     'slideUp 0.5s cubic-bezier(0.16,1,0.3,1) both',
        'scale-in':     'scaleIn 0.3s cubic-bezier(0.16,1,0.3,1) both',
        'shimmer':      'shimmer 2s linear infinite',
        'pulse-dot':    'pulseDot 2s ease-in-out infinite',
        'float':        'float 6s ease-in-out infinite',
        'float-slow':   'float 9s ease-in-out infinite',
        'spin-slow':    'spin 8s linear infinite',
        'orb-pulse':    'orbPulse 4s ease-in-out infinite',
        'build-scan':   'buildScan 2s ease-in-out infinite',
        'message-in':   'messageIn 0.3s cubic-bezier(0.16,1,0.3,1) both',
        'glow-pulse':   'glowPulse 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:     { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp:    { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:    { from: { opacity: '0', transform: 'scale(0.94)' }, to: { opacity: '1', transform: 'scale(1)' } },
        shimmer:    { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        pulseDot:   { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.3' } },
        float:      { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-12px)' } },
        orbPulse:   { '0%,100%': { transform: 'scale(1)', opacity: '0.6' }, '50%': { transform: 'scale(1.1)', opacity: '0.9' } },
        buildScan:  { '0%': { backgroundPosition: '-100% 0' }, '100%': { backgroundPosition: '200% 0' } },
        messageIn:  { from: { opacity: '0', transform: 'translateY(8px) scale(0.97)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
        glowPulse:  { '0%,100%': { boxShadow: '0 0 20px rgba(var(--brand-600-rgb),0.15)' }, '50%': { boxShadow: '0 0 40px rgba(var(--brand-600-rgb),0.35)' } },
      },
      backgroundImage: {
        'grid-pattern':      'linear-gradient(rgba(var(--brand-600-rgb),0.04) 1px,transparent 1px),linear-gradient(90deg,rgba(var(--brand-600-rgb),0.04) 1px,transparent 1px)',
        'radial-glow':       'radial-gradient(ellipse 80% 50% at 50% -10%,rgba(var(--brand-600-rgb),0.18),transparent)',
        'radial-glow-center':'radial-gradient(ellipse 60% 60% at 50% 50%,rgba(var(--brand-600-rgb),0.12),transparent)',
        'shimmer-gradient':  'linear-gradient(90deg,transparent 0%,rgba(var(--brand-600-rgb),0.15) 50%,transparent 100%)',
        'build-gradient':    'linear-gradient(90deg,transparent,rgba(var(--brand-600-rgb),0.2),rgba(var(--brand-500-rgb),0.3),rgba(var(--brand-600-rgb),0.2),transparent)',
        'glass-shine':       'linear-gradient(135deg,rgba(255,255,255,0.06) 0%,transparent 60%)',
      },
      backgroundSize: {
        'grid': '40px 40px',
      },
      boxShadow: {
        'glow-sm':   '0 0 20px rgba(var(--brand-600-rgb),0.12)',
        'glow':      '0 0 40px rgba(var(--brand-600-rgb),0.22)',
        'glow-lg':   '0 0 80px rgba(var(--brand-600-rgb),0.3)',
        'glass':     '0 1px 0 rgba(255,255,255,0.06) inset, 0 4px 24px rgba(0,0,0,0.5)',
        'card':      '0 1px 0 rgba(255,255,255,0.05) inset, 0 2px 8px rgba(0,0,0,0.4)',
        'modal':     '0 1px 0 rgba(255,255,255,0.08) inset, 0 24px 80px rgba(0,0,0,0.7)',
        'emerald':   '0 0 20px rgba(52,211,153,0.2)',
        'red':       '0 0 20px rgba(248,113,113,0.2)',
      },
      backdropBlur: {
        'xs': '4px',
      },
    },
  },
  plugins: [],
}
