ALTER TABLE "Site"
ADD COLUMN IF NOT EXISTS "ownershipClaimed" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "ownershipClaimedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "ownershipClaimedTo" TEXT;
